# Project information
site_name: Applied Linear Algebra
site_url: https://rbrooksdk.github.io/ALI1_25
site_author: Richard Brooks
site_description: Course page for Applied Linear Algebra at VIA University College
docs_dir: .
site_dir: ../site
# Repository information
repo_name: Github
repo_url: https://github.com/RBrooksDK/ALI1_25

# Copyright
copyright: Copyright &copy; 2025 Richard Brooks

# Configurations
theme:
  name: material
  language: en
  # custom_dir: overrides
  favicon: figures/ali.png
  logo: figures/ali.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  font:
    text: Roboto
    code: Red Hat Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

plugins:
  - same-dir
  - blog
  - search

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: material/email
      link: mailto:rib@via.dk
    - icon: fontawesome/brands/github
      link: https://github.com/RBrooksDK/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rbrooks-dk/

extra_css:
  - stylesheets/extra.css

nav:
  - Richard Brooks: https://rbrooksdk.github.io
  - Home: README.md
  - Sessions:
    - Sessions/README.md
    - 01 Introduction to Linear Algebra: 01_Introduction_to_Linear_Algebra/README.md
    - 02 Matrix Algebra: 02_Matrix_Algebra/README.md
    - 03 Determinants: 03_Determinants/README.md
    - 04 Vector Spaces: 04_Vector_Spaces/README.md
    - 05 Eigenvalues: 05_Eigenvalues/README.md
    - 06 Differential Equations: 06_Differential_Equations/README.md
    - 07 Orthogonality I: 07_Orthogonality_I/README.md
    - 08 Orthogonality II: 08_Orthogonality_II/README.md
    - 09 Symmetric Matrices, SVD, and PCA: 09_Symmetric_Matrices_SVD_and_PCA/README.md
    - 10 Recap and Conclusion: 10_Recap_and_Conclusion/README.md    
  - Exam: pages/exam.md
  - FAQ: pages/faq.md
  - Online Resources: pages/online_resources.md
  - General Resources ALI: https://viaucdk-my.sharepoint.com/:f:/g/personal/rib_viauc_dk/EqyrbL4eyEtPlLcHYKt3NfIBLLBs2xWNa4CtjvvZb5dKTw?e=HGyFGo